name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:

    runs-on: ${{ matrix.os }}
    name: "Test on ${{ matrix.os }} with Python v${{ matrix.py-version }}"
    strategy:
      matrix:
        py-version: [3.7, 3.8, 3.9]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.py-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.py-version }}

# As of now, we use the standard library only, so no dependencies
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run tests
      run: |
        python -m unittest discover -v -s ./tests -p test_*.py
